CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Accounts" (
    "AccountNumber" character varying(20) NOT NULL,
    "AccountName" character varying(256) NOT NULL,
    "Type" character varying(30) NOT NULL,
    "IsSummaryAccount" boolean NOT NULL,
    CONSTRAINT "PK_Accounts" PRIMARY KEY ("AccountNumber")
);

CREATE TABLE "JournalEntries" (
    "Id" uuid NOT NULL,
    "VoucherNumber" character varying(50) NOT NULL,
    "TransactionDate" timestamp with time zone NOT NULL,
    "Narration" character varying(500) NOT NULL,
    "Status" character varying(20) NOT NULL,
    CONSTRAINT "PK_JournalEntries" PRIMARY KEY ("Id")
);

CREATE TABLE "LedgerEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AccountNumber" character varying(20) NOT NULL,
    "Description" character varying(256) NOT NULL,
    "DebitAmount" numeric(18,2) NOT NULL,
    "CreditAmount" numeric(18,2) NOT NULL,
    "JournalEntryId" uuid NOT NULL,
    CONSTRAINT "PK_LedgerEntries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LedgerEntries_JournalEntries_JournalEntryId" FOREIGN KEY ("JournalEntryId") REFERENCES "JournalEntries" ("Id") ON DELETE CASCADE
);

INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('111', 'Tiền mặt', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('112', 'Tiền gửi Ngân hàng', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('131', 'Phải thu của khách hàng', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('152', 'Nguyên liệu, vật liệu', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('211', 'Tài sản cố định', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('331', 'Phải trả cho người bán', TRUE, 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('333', 'Thuế và các khoản phải nộp NN', TRUE, 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('334', 'Phải trả người lao động', TRUE, 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('411', 'Vốn đầu tư của chủ sở hữu', TRUE, 'Equity');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('511', 'Doanh thu bán hàng và CCDV', TRUE, 'Revenue');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('621', 'Chi phí NVL trực tiếp', TRUE, 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('641', 'Chi phí bán hàng', TRUE, 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('642', 'Chi phí QL doanh nghiệp', TRUE, 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('911', 'Xác định kết quả kinh doanh', TRUE, 'Other');

CREATE INDEX "IX_LedgerEntries_JournalEntryId" ON "LedgerEntries" ("JournalEntryId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251118052826_InitialMigration', '9.0.1');

UPDATE "Accounts" SET "AccountName" = 'Tiền gửi ngân hàng'
WHERE "AccountNumber" = '112';

UPDATE "Accounts" SET "AccountName" = 'Tài sản cố định hữu hình'
WHERE "AccountNumber" = '211';

UPDATE "Accounts" SET "AccountName" = 'Phải trả người lao động'
WHERE "AccountNumber" = '331';

UPDATE "Accounts" SET "AccountName" = 'Thuế và các khoản phải nộp nhà nước'
WHERE "AccountNumber" = '333';

UPDATE "Accounts" SET "AccountName" = 'Phải trả người mua'
WHERE "AccountNumber" = '334';

UPDATE "Accounts" SET "AccountName" = 'Doanh thu bán hàng và cung cấp dịch vụ'
WHERE "AccountNumber" = '511';

UPDATE "Accounts" SET "AccountName" = 'Chi phí nguyên vật liệu trực tiếp'
WHERE "AccountNumber" = '621';

UPDATE "Accounts" SET "AccountName" = 'Chi phí quản lý doanh nghiệp'
WHERE "AccountNumber" = '642';

INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('001', 'Tài sản thuê', TRUE, 'Other');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('002', 'Vật tư, hàng hóa nhận giữ hộ', TRUE, 'Other');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('003', 'Ký quỹ, ký cược', TRUE, 'Other');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('004', 'Chứng từ, sổ sách kế toán đã xử lý', TRUE, 'Other');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('005', 'Công cụ, dụng cụ không đủ tiêu chuẩn tài sản cố định', TRUE, 'Other');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('006', 'Tài sản thiếu chờ xử lý', TRUE, 'Other');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('007', 'Tài sản thừa chờ xử lý', TRUE, 'Other');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('008', 'Nợ khó đòi đã xử lý', TRUE, 'Other');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('009', 'Tài sản của đơn vị cấp trên giao', TRUE, 'Other');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('113', 'Tiền đang chuyển', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('121', 'Chứng khoán kinh doanh', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('128', 'Đầu tư nắm giữ đến ngày đáo hạn', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('133', 'Thuế GTGT được khấu trừ', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('136', 'Phải thu nội bộ', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('138', 'Phải thu khác', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('141', 'Tạm ứng', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('142', 'Chi phí trả trước', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('151', 'Hàng mua đang đi đường', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('153', 'Công cụ, dụng cụ', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('154', 'Chi phí sản xuất, kinh doanh dở dang', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('155', 'Thành phẩm', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('156', 'Hàng hóa', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('157', 'Hàng gửi đi bán', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('171', 'Gửi giữ kinh doanh chứng khoán', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('213', 'Tài sản cố định vô hình', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('214', 'Hao mòn tài sản cố định', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('221', 'Đầu tư vào công ty liên kết, liên doanh', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('222', 'Đầu tư góp vốn vào đơn vị khác', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('241', 'Xây dựng cơ bản dở dang', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('242', 'Bất động sản đầu tư dở dang', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('271', 'Gửi giữ kinh doanh chứng khoán (dài hạn)', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('272', 'Ký quỹ, ký cược dài hạn', TRUE, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('311', 'Phải trả cho người bán', TRUE, 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('315', 'Vay ngắn hạn', TRUE, 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('335', 'Chi phí phải trả', TRUE, 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('336', 'Phải trả nội bộ', TRUE, 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('337', 'Phải trả khách hàng', TRUE, 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('338', 'Phải trả khác', TRUE, 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('341', 'Vay dài hạn', TRUE, 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('343', 'Trái phiếu phát hành', TRUE, 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('344', 'Nhận ký quỹ dài hạn', TRUE, 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('412', 'Thặng dư vốn cổ phần', TRUE, 'Equity');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('413', 'Chênh lệch tỷ giá hối đoái', TRUE, 'Equity');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('414', 'Quỹ đầu tư phát triển', TRUE, 'Equity');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('415', 'Quỹ hỗ trợ sắp xếp doanh nghiệp', TRUE, 'Equity');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('417', 'Quỹ khen thưởng, phúc lợi', TRUE, 'Equity');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('418', 'Quỹ bình ổn giá', TRUE, 'Equity');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('419', 'Vốn góp của thành viên', TRUE, 'Equity');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('421', 'Lợi nhuận sau thuế chưa phân phối', TRUE, 'Equity');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('515', 'Doanh thu hoạt động tài chính', TRUE, 'Revenue');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('521', 'Các khoản giảm trừ doanh thu', TRUE, 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('531', 'Hàng bán bị trả lại', TRUE, 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('532', 'Chiết khấu thương mại', TRUE, 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('611', 'Mua hàng (hàng hóa, nguyên vật liệu)', TRUE, 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('622', 'Chi phí nhân công trực tiếp', TRUE, 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('623', 'Chi phí sản xuất chung', TRUE, 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('627', 'Chi phí quản lý doanh nghiệp', TRUE, 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('632', 'Giá vốn hàng bán', TRUE, 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('635', 'Chi phí tài chính', TRUE, 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('6421', 'Chi phí tiền lương', TRUE, 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('6422', 'Chi phí bảo hiểm, bảo hộ lao động', TRUE, 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Type")
VALUES ('811', 'Chi phí khác', TRUE, 'Expense');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251118085250_SeedInitialChartOfAccountsTT99', '9.0.1');

DELETE FROM "Accounts"
WHERE "AccountNumber" = '001';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '002';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '003';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '004';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '005';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '006';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '007';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '008';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '009';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '142';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '271';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '272';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '311';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '315';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '335';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '415';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '417';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '531';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '532';

DELETE FROM "Accounts"
WHERE "AccountNumber" = '611';

ALTER TABLE "Accounts" ADD "Level" integer NOT NULL DEFAULT 0;

ALTER TABLE "Accounts" ADD "ParentAccountNumber" character varying(20);

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '111';

UPDATE "Accounts" SET "AccountName" = 'Tiền gửi không kỳ hạn', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '112';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '113';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '121';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '128';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '131';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '133';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '136';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '138';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '141';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '151';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '152';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '153';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '154';

UPDATE "Accounts" SET "AccountName" = 'Sản phẩm', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '155';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '156';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '157';

UPDATE "Accounts" SET "AccountName" = 'Giao dịch mua, bán lại trái phiếu chính phủ', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '171';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '211';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '213';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL, "Type" = 'Expense'
WHERE "AccountNumber" = '214';

UPDATE "Accounts" SET "AccountName" = 'Đầu tư vào công ty con', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '221';

UPDATE "Accounts" SET "AccountName" = 'Đầu tư vào công ty liên doanh, liên kết', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '222';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '241';

UPDATE "Accounts" SET "AccountName" = 'Chi phí chờ phân bổ', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '242';

UPDATE "Accounts" SET "AccountName" = 'Phải trả cho người bán', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '331';

UPDATE "Accounts" SET "AccountName" = 'Thuế và các khoản phải nộp Nhà nước', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '333';

UPDATE "Accounts" SET "AccountName" = 'Phải trả người lao động', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '334';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '336';

UPDATE "Accounts" SET "AccountName" = 'Thanh toán tiền theo hợp đồng xây dựng', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '337';

UPDATE "Accounts" SET "AccountName" = 'Phải trả, phải nộp khác', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '338';

UPDATE "Accounts" SET "AccountName" = 'Vay và nợ thuê tài chính', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '341';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '343';

UPDATE "Accounts" SET "AccountName" = 'Nhận ký quỹ, ký cược', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '344';

UPDATE "Accounts" SET "AccountName" = 'Vốn chủ sở hữu', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '411';

UPDATE "Accounts" SET "AccountName" = 'Chênh lệch đánh giá lại tài sản', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '412';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '413';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '414';

UPDATE "Accounts" SET "AccountName" = 'Các quỹ khác thuộc vốn chủ sở hữu', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '418';

UPDATE "Accounts" SET "AccountName" = 'Cổ phiếu mua lại của chính mình', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '419';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '421';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '511';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '515';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL, "Type" = 'Revenue'
WHERE "AccountNumber" = '521';

UPDATE "Accounts" SET "AccountName" = 'Chi phí nguyên liệu, vật liệu trực tiếp', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '621';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '622';

UPDATE "Accounts" SET "AccountName" = 'Chi phí sử dụng máy thi công', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '623';

UPDATE "Accounts" SET "AccountName" = 'Chi phí sản xuất chung', "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '627';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '632';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '635';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '641';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '642';

UPDATE "Accounts" SET "AccountName" = 'Chi phí nhân viên quản lý', "IsSummaryAccount" = FALSE, "Level" = 2, "ParentAccountNumber" = '642'
WHERE "AccountNumber" = '6421';

UPDATE "Accounts" SET "AccountName" = 'Chi phí vật liệu văn phòng', "IsSummaryAccount" = FALSE, "Level" = 2, "ParentAccountNumber" = '642'
WHERE "AccountNumber" = '6422';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '811';

UPDATE "Accounts" SET "Level" = 1, "ParentAccountNumber" = NULL
WHERE "AccountNumber" = '911';

INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('1281', 'Tiền gửi có kỳ hạn', FALSE, 2, '128', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('1282', 'Trái phiếu', FALSE, 2, '128', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('1283', 'Cho vay', FALSE, 2, '128', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('1288', 'Các khoản đầu tư khác nắm giữ đến ngày đáo hạn', FALSE, 2, '128', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('1331', 'Thuế GTGT được khấu trừ của hàng hóa, dịch vụ', FALSE, 2, '133', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('1332', 'Thuế GTGT được khấu trừ của TSCĐ', FALSE, 2, '133', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('1361', 'Vốn kinh doanh ở đơn vị trực thuộc', FALSE, 2, '136', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('1362', 'Phải thu nội bộ về chênh lệch tỷ giá', FALSE, 2, '136', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('1363', 'Phải thu nội bộ về chi phí đi vay đủ điều kiện được vốn hóa', FALSE, 2, '136', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('1368', 'Phải thu nội bộ khác', FALSE, 2, '136', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('1381', 'Tài sản thiếu chờ xử lý', FALSE, 2, '138', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('1388', 'Phải thu khác', FALSE, 2, '138', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('158', 'Nguyên liệu, vật tư tại kho bảo thuế', TRUE, 1, NULL, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('212', 'Tài sản cố định thuê tài chính', TRUE, 1, NULL, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('2141', 'Hao mòn TSCĐ hữu hình', FALSE, 2, '214', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('2142', 'Hao mòn TSCĐ thuê tài chính', FALSE, 2, '214', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('2143', 'Hao mòn TSCĐ vô hình', FALSE, 2, '214', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('2147', 'Hao mòn BĐSĐT', FALSE, 2, '214', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('215', 'Tài sản sinh học', TRUE, 1, NULL, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('2151', 'Súc vật nuôi cho sản phẩm định kỳ', FALSE, 2, '215', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('21511', 'Súc vật nuôi cho sản phẩm định kỳ chưa đạt đến giai đoạn trưởng thành', FALSE, 3, '2151', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('21512', 'Súc vật nuôi cho sản phẩm định kỳ đạt đến giai đoạn trưởng thành', FALSE, 3, '2151', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('2152', 'Súc vật nuôi lấy sản phẩm một lần', FALSE, 2, '215', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('21521', 'Súc vật nuôi lấy sản phẩm một lần', FALSE, 3, '2152', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('2153', 'Cây trồng theo mùa vụ hoặc lấy sản phẩm một lần', FALSE, 2, '215', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('217', 'Bất động sản đầu tư', TRUE, 1, NULL, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('228', 'Đầu tư khác', TRUE, 1, NULL, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('2281', 'Đầu tư góp vốn vào đơn vị khác', FALSE, 2, '228', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('2282', 'Đầu tư khác', FALSE, 2, '228', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('229', 'Dự phòng tổn thất tài sản', TRUE, 1, NULL, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('2291', 'Dự phòng giảm giá chứng khoán kinh doanh', FALSE, 2, '229', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('2292', 'Dự phòng tổn thất đầu tư vào đơn vị khác', FALSE, 2, '229', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('2293', 'Dự phòng tổn thất các khoản đầu tư tài chính khác', FALSE, 2, '229', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('2294', 'Dự phòng giảm giá hàng tồn kho', FALSE, 2, '229', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('2295', 'Dự phòng tổn thất tài sản sinh học', FALSE, 2, '229', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('2411', 'Mua sắm TSCĐ', FALSE, 2, '241', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('2412', 'Xây dựng cơ bản', FALSE, 2, '241', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('2413', 'Sửa chữa, bảo dưỡng định kỳ TSCĐ', FALSE, 2, '241', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('2414', 'Nâng cấp, cải tạo TSCĐ', FALSE, 2, '241', 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('243', 'Tài sản thuế thu nhập hoãn lại', TRUE, 1, NULL, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('244', 'Ký quỹ, ký cược', TRUE, 1, NULL, 'Asset');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('332', 'Phải trả cổ tức, lợi nhuận', TRUE, 1, NULL, 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3331', 'Thuế GTGT phải nộp', FALSE, 2, '333', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3332', 'Thuế tiêu thụ đặc biệt', FALSE, 2, '333', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3333', 'Thuế xuất, nhập khẩu', FALSE, 2, '333', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3334', 'Thuế thu nhập doanh nghiệp', FALSE, 2, '333', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3335', 'Thuế thu nhập cá nhân', FALSE, 2, '333', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3336', 'Thuế tài nguyên', FALSE, 2, '333', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3337', 'Thuế đất, tiền thuê đất', FALSE, 2, '333', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3338', 'Thuế bảo vệ môi trường', FALSE, 2, '333', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3339', 'Phí, lệ phí và các khoản phải nộp khác', FALSE, 2, '333', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3361', 'Phải trả nội bộ về vốn kinh doanh', FALSE, 2, '336', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3362', 'Phải trả nội bộ về chênh lệch tỷ giá', FALSE, 2, '336', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3363', 'Phải trả nội bộ về chi phí đi vay đủ điều kiện được vốn hóa', FALSE, 2, '336', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3368', 'Phải trả nội bộ khác', FALSE, 2, '336', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3381', 'Tài sản thừa chờ giải quyết', FALSE, 2, '338', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3382', 'Kinh phí công đoàn', FALSE, 2, '338', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3383', 'Bảo hiểm xã hội', FALSE, 2, '338', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3384', 'Bảo hiểm y tế', FALSE, 2, '338', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3385', 'Bảo hiểm thất nghiệp', FALSE, 2, '338', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3387', 'Doanh thu chờ phân bổ', FALSE, 2, '338', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3388', 'Phải trả, phải nộp khác', FALSE, 2, '338', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3411', 'Các khoản vay', FALSE, 2, '341', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3412', 'Nợ thuê tài chính', FALSE, 2, '341', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3431', 'Trái phiếu thường', FALSE, 2, '343', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3432', 'Trái phiếu chuyển đổi', FALSE, 2, '343', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('347', 'Thuế thu nhập hoãn lại phải trả', TRUE, 1, NULL, 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('352', 'Dự phòng phải trả', TRUE, 1, NULL, 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3521', 'Dự phòng bảo hành sản phẩm, hàng hóa', FALSE, 2, '352', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3522', 'Dự phòng bảo hành công trình xây dựng', FALSE, 2, '352', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3523', 'Dự phòng tái cơ cấu doanh nghiệp', FALSE, 2, '352', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3525', 'Dự phòng phải trả khác', FALSE, 2, '352', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('353', 'Quỹ khen thưởng, phúc lợi', TRUE, 1, NULL, 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3531', 'Quỹ khen thưởng', FALSE, 2, '353', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3532', 'Quỹ phúc lợi', FALSE, 2, '353', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3533', 'Quỹ phúc lợi đã hình thành TSCĐ', FALSE, 2, '353', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3534', 'Quỹ phúc lợi quản lý điều hành công ty', FALSE, 2, '353', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('356', 'Quỹ phát triển khoa học và công nghệ', TRUE, 1, NULL, 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3561', 'Quỹ phát triển khoa học và công nghệ', FALSE, 2, '356', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('3562', 'Quỹ phát triển khoa học và công nghệ đã hình thành tài sản', FALSE, 2, '356', 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('357', 'Quỹ bình ổn giá', TRUE, 1, NULL, 'Liability');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('4111', 'Vốn góp của chủ sở hữu', FALSE, 2, '411', 'Equity');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('41111', 'Vốn góp của chủ sở hữu phổ thông có quyền biểu quyết', FALSE, 3, '4111', 'Equity');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('41112', 'Vốn góp khác', FALSE, 3, '4111', 'Equity');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('4112', 'Thặng dư vốn', FALSE, 2, '411', 'Equity');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('4118', 'Vốn khác', FALSE, 2, '411', 'Equity');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('4211', 'Lợi nhuận sau thuế chưa phân phối lũy kế đến cuối năm trước', FALSE, 2, '421', 'Equity');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('4212', 'Lợi nhuận sau thuế chưa phân phối năm nay', FALSE, 2, '421', 'Equity');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6231', 'Chi phí nhân công', FALSE, 2, '623', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6232', 'Chi phí vật liệu', FALSE, 2, '623', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6233', 'Chi phí dụng cụ sản xuất', FALSE, 2, '623', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6234', 'Chi phí dịch vụ mua ngoài', FALSE, 2, '623', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6238', 'Chi phí bằng tiền khác', FALSE, 2, '623', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6271', 'Chi phí nhân viên phân xưởng', FALSE, 2, '627', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6272', 'Chi phí vật liệu sản xuất', FALSE, 2, '627', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6273', 'Chi phí dụng cụ sản xuất', FALSE, 2, '627', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6274', 'Chi phí khấu hao TSCĐ', FALSE, 2, '627', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6275', 'Thuế, phí, lệ phí', FALSE, 2, '627', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6277', 'Chi phí dịch vụ mua ngoài', FALSE, 2, '627', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6278', 'Chi phí bằng tiền khác', FALSE, 2, '627', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6411', 'Chi phí nhân viên bán hàng', FALSE, 2, '641', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6412', 'Chi phí vật liệu, bao bì', FALSE, 2, '641', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6413', 'Chi phí dụng cụ, vật tư', FALSE, 2, '641', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6414', 'Chi phí khấu hao TSCĐ', FALSE, 2, '641', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6415', 'Thuế, phí, lệ phí', FALSE, 2, '641', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6417', 'Chi phí dịch vụ mua ngoài', FALSE, 2, '641', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6418', 'Chi phí bằng tiền khác', FALSE, 2, '641', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6423', 'Chi phí đồ dùng văn phòng', FALSE, 2, '642', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6424', 'Chi phí khấu hao TSCĐ', FALSE, 2, '642', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6425', 'Thuế, phí, lệ phí', FALSE, 2, '642', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6426', 'Chi phí dự phòng', FALSE, 2, '642', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6427', 'Chi phí dịch vụ mua ngoài', FALSE, 2, '642', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('6428', 'Chi phí bằng tiền khác', FALSE, 2, '642', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('711', 'Thu nhập khác', TRUE, 1, NULL, 'Revenue');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('821', 'Chi phí thuế thu nhập doanh nghiệp', TRUE, 1, NULL, 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('8211', 'Chi phí thuế TNDN hiện hành', FALSE, 2, '821', 'Expense');
INSERT INTO "Accounts" ("AccountNumber", "AccountName", "IsSummaryAccount", "Level", "ParentAccountNumber", "Type")
VALUES ('8212', 'Chi phí thuế TNDN hoãn lại', FALSE, 2, '821', 'Expense');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251118093146_UpdateAccountEntityAndSeedData', '9.0.1');

COMMIT;

