# gl_core/config/reports/b01_dnn.yaml
report: B01-DNN
name: "Bảng cân đối kế toán"
structure:
  - group: "A. TÀI SẢN NGẮN HẠN"
    lines:
      - label: "1. Tiền và các khoản tương đương tiền"
        accounts: ["1111", "1121", "113"]  # Thay vì ["111", "112", "113"]
        sign: "debit"
      - label: "2. Các khoản đầu tư tài chính ngắn hạn"
        accounts: ["121", "128"]
        sign: "debit"
      - label: "3. Phải thu ngắn hạn"
        accounts: ["131", "136", "138", "141"]
        sign: "debit"
      - label: "4. Hàng tồn kho"
        accounts: ["152", "153", "154", "155", "156", "157", "159"]
        sign: "debit"
      - label: "5. Tài sản ngắn hạn khác"
        accounts: ["244"]
        sign: "debit"

  - group: "B. TÀI SẢN DÀI HẠN"
    lines:
      - label: "6. Tài sản cố định"
        accounts: ["211", "213", "214"]
        sign: "debit"
      - label: "7. Tài sản dài hạn khác"
        accounts: ["242"]
        sign: "debit"

  - group: "C. NỢ PHẢI TRẢ"
    lines:
      - label: "8. Phải trả người bán"
        accounts: ["331"]
        sign: "credit"
      - label: "9. Người lao động"
        accounts: ["334"]
        sign: "credit"
      - label: "10. Thuế và các khoản phải nộp nhà nước"
        accounts: ["3331", "3332", "3333", "3334", "3335", "3337", "3338"]
        sign: "credit"
      - label: "11. Phải trả khác"
        accounts: ["338"]
        sign: "credit"

  - group: "D. VỐN CHỦ SỞ HỮU"
    lines:
      - label: "12. Vốn đầu tư của chủ sở hữu"
        accounts: ["411"]
        sign: "credit"
      - label: "13. Lợi nhuận sau thuế chưa phân phối"
        accounts: ["421"]
        sign: "credit"