"""Add GIA_VON and THU_NHAP_KHAC to LoaiTaiKhoan enum

Revision ID: 8e7bd485b202
Revises: 
Create Date: 2025-11-28 13:42:43.441849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e7bd485b202'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    # op.drop_table('journal_entries')
    # op.drop_index(op.f('ix_journal_entry_lines_id'), table_name='journal_entry_lines')
    # op.drop_table('journal_entry_lines')
    # op.drop_index(op.f('ix_accounting_periods_id'), table_name='accounting_periods')
    # op.drop_table('accounting_periods')
    # op.drop_index(op.f('ix_accounts_so_tai_khoan'), table_name='accounts')
    # op.drop_table('accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('so_tai_khoan', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('ten_tai_khoan', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('loai_tai_khoan', postgresql.ENUM('TAI_SAN', 'NO_PHAI_TRA', 'VON_CHU_SO_HUU', 'DOANH_THU', 'CHI_PHI', 'KHAC', name='loaitaikhoan'), autoincrement=False, nullable=False),
    sa.Column('cap_tai_khoan', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('so_tai_khoan_cha', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('la_tai_khoan_tong_hop', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['so_tai_khoan_cha'], ['accounts.so_tai_khoan'], name='accounts_so_tai_khoan_cha_fkey'),
    sa.PrimaryKeyConstraint('so_tai_khoan', name='accounts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_accounts_so_tai_khoan'), 'accounts', ['so_tai_khoan'], unique=False)
    op.create_table('accounting_periods',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ten_ky', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ngay_bat_dau', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ngay_ket_thuc', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('trang_thai', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('ghi_chu', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('accounting_periods_pkey')),
    sa.UniqueConstraint('ten_ky', name=op.f('accounting_periods_ten_ky_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_accounting_periods_id'), 'accounting_periods', ['id'], unique=False)
    op.create_table('journal_entry_lines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('journal_entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('so_tai_khoan', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('no', sa.NUMERIC(precision=19, scale=4), autoincrement=False, nullable=False),
    sa.Column('co', sa.NUMERIC(precision=19, scale=4), autoincrement=False, nullable=False),
    sa.Column('mo_ta', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('journal_entry_lines_journal_entry_id_fkey')),
    sa.ForeignKeyConstraint(['so_tai_khoan'], ['accounts.so_tai_khoan'], name=op.f('journal_entry_lines_so_tai_khoan_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('journal_entry_lines_pkey'))
    )
    op.create_index(op.f('ix_journal_entry_lines_id'), 'journal_entry_lines', ['id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ngay_ct', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('so_phieu', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mo_ta', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('trang_thai', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('journal_entries_pkey')),
    sa.UniqueConstraint('so_phieu', name=op.f('journal_entries_so_phieu_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    # ### end Alembic commands ###
