// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TT99.INFR.Data;

#nullable disable

namespace TT99.INFR.Migrations
{
    [DbContext(typeof(TT99DbContext))]
    [Migration("20251118093146_UpdateAccountEntityAndSeedData")]
    partial class UpdateAccountEntityAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TT99.DMN.Ents.Account", b =>
                {
                    b.Property<string>("AccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsSummaryAccount")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("ParentAccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("AccountNumber");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountNumber = "111",
                            AccountName = "Tiền mặt",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "112",
                            AccountName = "Tiền gửi không kỳ hạn",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "113",
                            AccountName = "Tiền đang chuyển",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "121",
                            AccountName = "Chứng khoán kinh doanh",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "128",
                            AccountName = "Đầu tư nắm giữ đến ngày đáo hạn",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "131",
                            AccountName = "Phải thu của khách hàng",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "133",
                            AccountName = "Thuế GTGT được khấu trừ",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "136",
                            AccountName = "Phải thu nội bộ",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "138",
                            AccountName = "Phải thu khác",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "141",
                            AccountName = "Tạm ứng",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "151",
                            AccountName = "Hàng mua đang đi đường",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "152",
                            AccountName = "Nguyên liệu, vật liệu",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "153",
                            AccountName = "Công cụ, dụng cụ",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "154",
                            AccountName = "Chi phí sản xuất, kinh doanh dở dang",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "155",
                            AccountName = "Sản phẩm",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "156",
                            AccountName = "Hàng hóa",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "157",
                            AccountName = "Hàng gửi đi bán",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "158",
                            AccountName = "Nguyên liệu, vật tư tại kho bảo thuế",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "171",
                            AccountName = "Giao dịch mua, bán lại trái phiếu chính phủ",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "211",
                            AccountName = "Tài sản cố định hữu hình",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "212",
                            AccountName = "Tài sản cố định thuê tài chính",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "213",
                            AccountName = "Tài sản cố định vô hình",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "214",
                            AccountName = "Hao mòn tài sản cố định",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "215",
                            AccountName = "Tài sản sinh học",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "217",
                            AccountName = "Bất động sản đầu tư",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "221",
                            AccountName = "Đầu tư vào công ty con",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "222",
                            AccountName = "Đầu tư vào công ty liên doanh, liên kết",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "228",
                            AccountName = "Đầu tư khác",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "229",
                            AccountName = "Dự phòng tổn thất tài sản",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "241",
                            AccountName = "Xây dựng cơ bản dở dang",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "242",
                            AccountName = "Chi phí chờ phân bổ",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "243",
                            AccountName = "Tài sản thuế thu nhập hoãn lại",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "244",
                            AccountName = "Ký quỹ, ký cược",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "1281",
                            AccountName = "Tiền gửi có kỳ hạn",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "128",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "1282",
                            AccountName = "Trái phiếu",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "128",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "1283",
                            AccountName = "Cho vay",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "128",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "1288",
                            AccountName = "Các khoản đầu tư khác nắm giữ đến ngày đáo hạn",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "128",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "1331",
                            AccountName = "Thuế GTGT được khấu trừ của hàng hóa, dịch vụ",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "133",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "1332",
                            AccountName = "Thuế GTGT được khấu trừ của TSCĐ",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "133",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "1361",
                            AccountName = "Vốn kinh doanh ở đơn vị trực thuộc",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "136",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "1362",
                            AccountName = "Phải thu nội bộ về chênh lệch tỷ giá",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "136",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "1363",
                            AccountName = "Phải thu nội bộ về chi phí đi vay đủ điều kiện được vốn hóa",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "136",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "1368",
                            AccountName = "Phải thu nội bộ khác",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "136",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "1381",
                            AccountName = "Tài sản thiếu chờ xử lý",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "138",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "1388",
                            AccountName = "Phải thu khác",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "138",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "2141",
                            AccountName = "Hao mòn TSCĐ hữu hình",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "214",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "2142",
                            AccountName = "Hao mòn TSCĐ thuê tài chính",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "214",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "2143",
                            AccountName = "Hao mòn TSCĐ vô hình",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "214",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "2147",
                            AccountName = "Hao mòn BĐSĐT",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "214",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "2151",
                            AccountName = "Súc vật nuôi cho sản phẩm định kỳ",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "215",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "21511",
                            AccountName = "Súc vật nuôi cho sản phẩm định kỳ chưa đạt đến giai đoạn trưởng thành",
                            IsSummaryAccount = false,
                            Level = 3,
                            ParentAccountNumber = "2151",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "21512",
                            AccountName = "Súc vật nuôi cho sản phẩm định kỳ đạt đến giai đoạn trưởng thành",
                            IsSummaryAccount = false,
                            Level = 3,
                            ParentAccountNumber = "2151",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "2152",
                            AccountName = "Súc vật nuôi lấy sản phẩm một lần",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "215",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "21521",
                            AccountName = "Súc vật nuôi lấy sản phẩm một lần",
                            IsSummaryAccount = false,
                            Level = 3,
                            ParentAccountNumber = "2152",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "2153",
                            AccountName = "Cây trồng theo mùa vụ hoặc lấy sản phẩm một lần",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "215",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "2281",
                            AccountName = "Đầu tư góp vốn vào đơn vị khác",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "228",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "2282",
                            AccountName = "Đầu tư khác",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "228",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "2291",
                            AccountName = "Dự phòng giảm giá chứng khoán kinh doanh",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "229",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "2292",
                            AccountName = "Dự phòng tổn thất đầu tư vào đơn vị khác",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "229",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "2293",
                            AccountName = "Dự phòng tổn thất các khoản đầu tư tài chính khác",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "229",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "2294",
                            AccountName = "Dự phòng giảm giá hàng tồn kho",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "229",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "2295",
                            AccountName = "Dự phòng tổn thất tài sản sinh học",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "229",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "2411",
                            AccountName = "Mua sắm TSCĐ",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "241",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "2412",
                            AccountName = "Xây dựng cơ bản",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "241",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "2413",
                            AccountName = "Sửa chữa, bảo dưỡng định kỳ TSCĐ",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "241",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "2414",
                            AccountName = "Nâng cấp, cải tạo TSCĐ",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "241",
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "331",
                            AccountName = "Phải trả cho người bán",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "332",
                            AccountName = "Phải trả cổ tức, lợi nhuận",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "333",
                            AccountName = "Thuế và các khoản phải nộp Nhà nước",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "334",
                            AccountName = "Phải trả người lao động",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "336",
                            AccountName = "Phải trả nội bộ",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "337",
                            AccountName = "Thanh toán tiền theo hợp đồng xây dựng",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "338",
                            AccountName = "Phải trả, phải nộp khác",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "341",
                            AccountName = "Vay và nợ thuê tài chính",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "343",
                            AccountName = "Trái phiếu phát hành",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "344",
                            AccountName = "Nhận ký quỹ, ký cược",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "347",
                            AccountName = "Thuế thu nhập hoãn lại phải trả",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "352",
                            AccountName = "Dự phòng phải trả",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "353",
                            AccountName = "Quỹ khen thưởng, phúc lợi",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "356",
                            AccountName = "Quỹ phát triển khoa học và công nghệ",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "357",
                            AccountName = "Quỹ bình ổn giá",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3331",
                            AccountName = "Thuế GTGT phải nộp",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "333",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3332",
                            AccountName = "Thuế tiêu thụ đặc biệt",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "333",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3333",
                            AccountName = "Thuế xuất, nhập khẩu",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "333",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3334",
                            AccountName = "Thuế thu nhập doanh nghiệp",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "333",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3335",
                            AccountName = "Thuế thu nhập cá nhân",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "333",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3336",
                            AccountName = "Thuế tài nguyên",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "333",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3337",
                            AccountName = "Thuế đất, tiền thuê đất",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "333",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3338",
                            AccountName = "Thuế bảo vệ môi trường",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "333",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3339",
                            AccountName = "Phí, lệ phí và các khoản phải nộp khác",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "333",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3361",
                            AccountName = "Phải trả nội bộ về vốn kinh doanh",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "336",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3362",
                            AccountName = "Phải trả nội bộ về chênh lệch tỷ giá",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "336",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3363",
                            AccountName = "Phải trả nội bộ về chi phí đi vay đủ điều kiện được vốn hóa",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "336",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3368",
                            AccountName = "Phải trả nội bộ khác",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "336",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3381",
                            AccountName = "Tài sản thừa chờ giải quyết",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "338",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3382",
                            AccountName = "Kinh phí công đoàn",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "338",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3383",
                            AccountName = "Bảo hiểm xã hội",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "338",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3384",
                            AccountName = "Bảo hiểm y tế",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "338",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3385",
                            AccountName = "Bảo hiểm thất nghiệp",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "338",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3387",
                            AccountName = "Doanh thu chờ phân bổ",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "338",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3388",
                            AccountName = "Phải trả, phải nộp khác",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "338",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3411",
                            AccountName = "Các khoản vay",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "341",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3412",
                            AccountName = "Nợ thuê tài chính",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "341",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3431",
                            AccountName = "Trái phiếu thường",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "343",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3432",
                            AccountName = "Trái phiếu chuyển đổi",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "343",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3521",
                            AccountName = "Dự phòng bảo hành sản phẩm, hàng hóa",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "352",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3522",
                            AccountName = "Dự phòng bảo hành công trình xây dựng",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "352",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3523",
                            AccountName = "Dự phòng tái cơ cấu doanh nghiệp",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "352",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3525",
                            AccountName = "Dự phòng phải trả khác",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "352",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3531",
                            AccountName = "Quỹ khen thưởng",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "353",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3532",
                            AccountName = "Quỹ phúc lợi",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "353",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3533",
                            AccountName = "Quỹ phúc lợi đã hình thành TSCĐ",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "353",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3534",
                            AccountName = "Quỹ phúc lợi quản lý điều hành công ty",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "353",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3561",
                            AccountName = "Quỹ phát triển khoa học và công nghệ",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "356",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "3562",
                            AccountName = "Quỹ phát triển khoa học và công nghệ đã hình thành tài sản",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "356",
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "411",
                            AccountName = "Vốn chủ sở hữu",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "412",
                            AccountName = "Chênh lệch đánh giá lại tài sản",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "413",
                            AccountName = "Chênh lệch tỷ giá hối đoái",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "414",
                            AccountName = "Quỹ đầu tư phát triển",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "418",
                            AccountName = "Các quỹ khác thuộc vốn chủ sở hữu",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "419",
                            AccountName = "Cổ phiếu mua lại của chính mình",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "421",
                            AccountName = "Lợi nhuận sau thuế chưa phân phối",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "4111",
                            AccountName = "Vốn góp của chủ sở hữu",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "411",
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "4112",
                            AccountName = "Thặng dư vốn",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "411",
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "4118",
                            AccountName = "Vốn khác",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "411",
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "41111",
                            AccountName = "Vốn góp của chủ sở hữu phổ thông có quyền biểu quyết",
                            IsSummaryAccount = false,
                            Level = 3,
                            ParentAccountNumber = "4111",
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "41112",
                            AccountName = "Vốn góp khác",
                            IsSummaryAccount = false,
                            Level = 3,
                            ParentAccountNumber = "4111",
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "4211",
                            AccountName = "Lợi nhuận sau thuế chưa phân phối lũy kế đến cuối năm trước",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "421",
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "4212",
                            AccountName = "Lợi nhuận sau thuế chưa phân phối năm nay",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "421",
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "511",
                            AccountName = "Doanh thu bán hàng và cung cấp dịch vụ",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Revenue"
                        },
                        new
                        {
                            AccountNumber = "515",
                            AccountName = "Doanh thu hoạt động tài chính",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Revenue"
                        },
                        new
                        {
                            AccountNumber = "521",
                            AccountName = "Các khoản giảm trừ doanh thu",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Revenue"
                        },
                        new
                        {
                            AccountNumber = "621",
                            AccountName = "Chi phí nguyên liệu, vật liệu trực tiếp",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "622",
                            AccountName = "Chi phí nhân công trực tiếp",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "623",
                            AccountName = "Chi phí sử dụng máy thi công",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "627",
                            AccountName = "Chi phí sản xuất chung",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "632",
                            AccountName = "Giá vốn hàng bán",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "635",
                            AccountName = "Chi phí tài chính",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "641",
                            AccountName = "Chi phí bán hàng",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "642",
                            AccountName = "Chi phí quản lý doanh nghiệp",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6231",
                            AccountName = "Chi phí nhân công",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "623",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6232",
                            AccountName = "Chi phí vật liệu",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "623",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6233",
                            AccountName = "Chi phí dụng cụ sản xuất",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "623",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6234",
                            AccountName = "Chi phí dịch vụ mua ngoài",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "623",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6238",
                            AccountName = "Chi phí bằng tiền khác",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "623",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6271",
                            AccountName = "Chi phí nhân viên phân xưởng",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "627",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6272",
                            AccountName = "Chi phí vật liệu sản xuất",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "627",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6273",
                            AccountName = "Chi phí dụng cụ sản xuất",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "627",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6274",
                            AccountName = "Chi phí khấu hao TSCĐ",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "627",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6275",
                            AccountName = "Thuế, phí, lệ phí",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "627",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6277",
                            AccountName = "Chi phí dịch vụ mua ngoài",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "627",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6278",
                            AccountName = "Chi phí bằng tiền khác",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "627",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6411",
                            AccountName = "Chi phí nhân viên bán hàng",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "641",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6412",
                            AccountName = "Chi phí vật liệu, bao bì",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "641",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6413",
                            AccountName = "Chi phí dụng cụ, vật tư",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "641",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6414",
                            AccountName = "Chi phí khấu hao TSCĐ",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "641",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6415",
                            AccountName = "Thuế, phí, lệ phí",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "641",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6417",
                            AccountName = "Chi phí dịch vụ mua ngoài",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "641",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6418",
                            AccountName = "Chi phí bằng tiền khác",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "641",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6421",
                            AccountName = "Chi phí nhân viên quản lý",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "642",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6422",
                            AccountName = "Chi phí vật liệu văn phòng",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "642",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6423",
                            AccountName = "Chi phí đồ dùng văn phòng",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "642",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6424",
                            AccountName = "Chi phí khấu hao TSCĐ",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "642",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6425",
                            AccountName = "Thuế, phí, lệ phí",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "642",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6426",
                            AccountName = "Chi phí dự phòng",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "642",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6427",
                            AccountName = "Chi phí dịch vụ mua ngoài",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "642",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6428",
                            AccountName = "Chi phí bằng tiền khác",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "642",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "711",
                            AccountName = "Thu nhập khác",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Revenue"
                        },
                        new
                        {
                            AccountNumber = "811",
                            AccountName = "Chi phí khác",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "821",
                            AccountName = "Chi phí thuế thu nhập doanh nghiệp",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "8211",
                            AccountName = "Chi phí thuế TNDN hiện hành",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "821",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "8212",
                            AccountName = "Chi phí thuế TNDN hoãn lại",
                            IsSummaryAccount = false,
                            Level = 2,
                            ParentAccountNumber = "821",
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "911",
                            AccountName = "Xác định kết quả kinh doanh",
                            IsSummaryAccount = true,
                            Level = 1,
                            Type = "Other"
                        });
                });

            modelBuilder.Entity("TT99.DMN.Ents.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Narration")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VoucherNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("TT99.DMN.Ents.JournalEntry", b =>
                {
                    b.OwnsMany("TT99.DMN.Ents.LedgerEntry", "Entries", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AccountNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<decimal>("CreditAmount")
                                .HasColumnType("decimal(18, 2)");

                            b1.Property<decimal>("DebitAmount")
                                .HasColumnType("decimal(18, 2)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<Guid>("JournalEntryId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("JournalEntryId");

                            b1.ToTable("LedgerEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JournalEntryId");
                        });

                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
