// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TT99.INFR.Data;

#nullable disable

namespace TT99.INFR.Migrations
{
    [DbContext(typeof(TT99DbContext))]
    [Migration("20251118052826_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TT99.DMN.Ents.Account", b =>
                {
                    b.Property<string>("AccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsSummaryAccount")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("AccountNumber");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountNumber = "111",
                            AccountName = "Tiền mặt",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "112",
                            AccountName = "Tiền gửi Ngân hàng",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "131",
                            AccountName = "Phải thu của khách hàng",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "152",
                            AccountName = "Nguyên liệu, vật liệu",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "211",
                            AccountName = "Tài sản cố định",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "331",
                            AccountName = "Phải trả cho người bán",
                            IsSummaryAccount = true,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "333",
                            AccountName = "Thuế và các khoản phải nộp NN",
                            IsSummaryAccount = true,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "334",
                            AccountName = "Phải trả người lao động",
                            IsSummaryAccount = true,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "411",
                            AccountName = "Vốn đầu tư của chủ sở hữu",
                            IsSummaryAccount = true,
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "511",
                            AccountName = "Doanh thu bán hàng và CCDV",
                            IsSummaryAccount = true,
                            Type = "Revenue"
                        },
                        new
                        {
                            AccountNumber = "621",
                            AccountName = "Chi phí NVL trực tiếp",
                            IsSummaryAccount = true,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "641",
                            AccountName = "Chi phí bán hàng",
                            IsSummaryAccount = true,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "642",
                            AccountName = "Chi phí QL doanh nghiệp",
                            IsSummaryAccount = true,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "911",
                            AccountName = "Xác định kết quả kinh doanh",
                            IsSummaryAccount = true,
                            Type = "Other"
                        });
                });

            modelBuilder.Entity("TT99.DMN.Ents.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Narration")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VoucherNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("TT99.DMN.Ents.JournalEntry", b =>
                {
                    b.OwnsMany("TT99.DMN.Ents.LedgerEntry", "Entries", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AccountNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<decimal>("CreditAmount")
                                .HasColumnType("decimal(18, 2)");

                            b1.Property<decimal>("DebitAmount")
                                .HasColumnType("decimal(18, 2)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<Guid>("JournalEntryId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("JournalEntryId");

                            b1.ToTable("LedgerEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JournalEntryId");
                        });

                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
