// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TT99.INFR.Data;

#nullable disable

namespace TT99.INFR.Migrations
{
    [DbContext(typeof(TT99DbContext))]
    [Migration("20251118085250_SeedInitialChartOfAccountsTT99")]
    partial class SeedInitialChartOfAccountsTT99
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TT99.DMN.Ents.Account", b =>
                {
                    b.Property<string>("AccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsSummaryAccount")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("AccountNumber");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountNumber = "111",
                            AccountName = "Tiền mặt",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "112",
                            AccountName = "Tiền gửi ngân hàng",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "113",
                            AccountName = "Tiền đang chuyển",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "121",
                            AccountName = "Chứng khoán kinh doanh",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "128",
                            AccountName = "Đầu tư nắm giữ đến ngày đáo hạn",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "131",
                            AccountName = "Phải thu của khách hàng",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "133",
                            AccountName = "Thuế GTGT được khấu trừ",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "136",
                            AccountName = "Phải thu nội bộ",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "138",
                            AccountName = "Phải thu khác",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "141",
                            AccountName = "Tạm ứng",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "142",
                            AccountName = "Chi phí trả trước",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "151",
                            AccountName = "Hàng mua đang đi đường",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "152",
                            AccountName = "Nguyên liệu, vật liệu",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "153",
                            AccountName = "Công cụ, dụng cụ",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "154",
                            AccountName = "Chi phí sản xuất, kinh doanh dở dang",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "155",
                            AccountName = "Thành phẩm",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "156",
                            AccountName = "Hàng hóa",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "157",
                            AccountName = "Hàng gửi đi bán",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "171",
                            AccountName = "Gửi giữ kinh doanh chứng khoán",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "211",
                            AccountName = "Tài sản cố định hữu hình",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "213",
                            AccountName = "Tài sản cố định vô hình",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "214",
                            AccountName = "Hao mòn tài sản cố định",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "221",
                            AccountName = "Đầu tư vào công ty liên kết, liên doanh",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "222",
                            AccountName = "Đầu tư góp vốn vào đơn vị khác",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "241",
                            AccountName = "Xây dựng cơ bản dở dang",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "242",
                            AccountName = "Bất động sản đầu tư dở dang",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "271",
                            AccountName = "Gửi giữ kinh doanh chứng khoán (dài hạn)",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "272",
                            AccountName = "Ký quỹ, ký cược dài hạn",
                            IsSummaryAccount = true,
                            Type = "Asset"
                        },
                        new
                        {
                            AccountNumber = "311",
                            AccountName = "Phải trả cho người bán",
                            IsSummaryAccount = true,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "315",
                            AccountName = "Vay ngắn hạn",
                            IsSummaryAccount = true,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "331",
                            AccountName = "Phải trả người lao động",
                            IsSummaryAccount = true,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "333",
                            AccountName = "Thuế và các khoản phải nộp nhà nước",
                            IsSummaryAccount = true,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "334",
                            AccountName = "Phải trả người mua",
                            IsSummaryAccount = true,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "335",
                            AccountName = "Chi phí phải trả",
                            IsSummaryAccount = true,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "336",
                            AccountName = "Phải trả nội bộ",
                            IsSummaryAccount = true,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "337",
                            AccountName = "Phải trả khách hàng",
                            IsSummaryAccount = true,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "338",
                            AccountName = "Phải trả khác",
                            IsSummaryAccount = true,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "341",
                            AccountName = "Vay dài hạn",
                            IsSummaryAccount = true,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "343",
                            AccountName = "Trái phiếu phát hành",
                            IsSummaryAccount = true,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "344",
                            AccountName = "Nhận ký quỹ dài hạn",
                            IsSummaryAccount = true,
                            Type = "Liability"
                        },
                        new
                        {
                            AccountNumber = "411",
                            AccountName = "Vốn đầu tư của chủ sở hữu",
                            IsSummaryAccount = true,
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "412",
                            AccountName = "Thặng dư vốn cổ phần",
                            IsSummaryAccount = true,
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "413",
                            AccountName = "Chênh lệch tỷ giá hối đoái",
                            IsSummaryAccount = true,
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "414",
                            AccountName = "Quỹ đầu tư phát triển",
                            IsSummaryAccount = true,
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "415",
                            AccountName = "Quỹ hỗ trợ sắp xếp doanh nghiệp",
                            IsSummaryAccount = true,
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "417",
                            AccountName = "Quỹ khen thưởng, phúc lợi",
                            IsSummaryAccount = true,
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "418",
                            AccountName = "Quỹ bình ổn giá",
                            IsSummaryAccount = true,
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "419",
                            AccountName = "Vốn góp của thành viên",
                            IsSummaryAccount = true,
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "421",
                            AccountName = "Lợi nhuận sau thuế chưa phân phối",
                            IsSummaryAccount = true,
                            Type = "Equity"
                        },
                        new
                        {
                            AccountNumber = "511",
                            AccountName = "Doanh thu bán hàng và cung cấp dịch vụ",
                            IsSummaryAccount = true,
                            Type = "Revenue"
                        },
                        new
                        {
                            AccountNumber = "515",
                            AccountName = "Doanh thu hoạt động tài chính",
                            IsSummaryAccount = true,
                            Type = "Revenue"
                        },
                        new
                        {
                            AccountNumber = "521",
                            AccountName = "Các khoản giảm trừ doanh thu",
                            IsSummaryAccount = true,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "531",
                            AccountName = "Hàng bán bị trả lại",
                            IsSummaryAccount = true,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "532",
                            AccountName = "Chiết khấu thương mại",
                            IsSummaryAccount = true,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "611",
                            AccountName = "Mua hàng (hàng hóa, nguyên vật liệu)",
                            IsSummaryAccount = true,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "621",
                            AccountName = "Chi phí nguyên vật liệu trực tiếp",
                            IsSummaryAccount = true,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "622",
                            AccountName = "Chi phí nhân công trực tiếp",
                            IsSummaryAccount = true,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "623",
                            AccountName = "Chi phí sản xuất chung",
                            IsSummaryAccount = true,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "627",
                            AccountName = "Chi phí quản lý doanh nghiệp",
                            IsSummaryAccount = true,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "632",
                            AccountName = "Giá vốn hàng bán",
                            IsSummaryAccount = true,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "635",
                            AccountName = "Chi phí tài chính",
                            IsSummaryAccount = true,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "641",
                            AccountName = "Chi phí bán hàng",
                            IsSummaryAccount = true,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "642",
                            AccountName = "Chi phí quản lý doanh nghiệp",
                            IsSummaryAccount = true,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6421",
                            AccountName = "Chi phí tiền lương",
                            IsSummaryAccount = true,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "6422",
                            AccountName = "Chi phí bảo hiểm, bảo hộ lao động",
                            IsSummaryAccount = true,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "811",
                            AccountName = "Chi phí khác",
                            IsSummaryAccount = true,
                            Type = "Expense"
                        },
                        new
                        {
                            AccountNumber = "911",
                            AccountName = "Xác định kết quả kinh doanh",
                            IsSummaryAccount = true,
                            Type = "Other"
                        },
                        new
                        {
                            AccountNumber = "001",
                            AccountName = "Tài sản thuê",
                            IsSummaryAccount = true,
                            Type = "Other"
                        },
                        new
                        {
                            AccountNumber = "002",
                            AccountName = "Vật tư, hàng hóa nhận giữ hộ",
                            IsSummaryAccount = true,
                            Type = "Other"
                        },
                        new
                        {
                            AccountNumber = "003",
                            AccountName = "Ký quỹ, ký cược",
                            IsSummaryAccount = true,
                            Type = "Other"
                        },
                        new
                        {
                            AccountNumber = "004",
                            AccountName = "Chứng từ, sổ sách kế toán đã xử lý",
                            IsSummaryAccount = true,
                            Type = "Other"
                        },
                        new
                        {
                            AccountNumber = "005",
                            AccountName = "Công cụ, dụng cụ không đủ tiêu chuẩn tài sản cố định",
                            IsSummaryAccount = true,
                            Type = "Other"
                        },
                        new
                        {
                            AccountNumber = "006",
                            AccountName = "Tài sản thiếu chờ xử lý",
                            IsSummaryAccount = true,
                            Type = "Other"
                        },
                        new
                        {
                            AccountNumber = "007",
                            AccountName = "Tài sản thừa chờ xử lý",
                            IsSummaryAccount = true,
                            Type = "Other"
                        },
                        new
                        {
                            AccountNumber = "008",
                            AccountName = "Nợ khó đòi đã xử lý",
                            IsSummaryAccount = true,
                            Type = "Other"
                        },
                        new
                        {
                            AccountNumber = "009",
                            AccountName = "Tài sản của đơn vị cấp trên giao",
                            IsSummaryAccount = true,
                            Type = "Other"
                        });
                });

            modelBuilder.Entity("TT99.DMN.Ents.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Narration")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VoucherNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("TT99.DMN.Ents.JournalEntry", b =>
                {
                    b.OwnsMany("TT99.DMN.Ents.LedgerEntry", "Entries", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AccountNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<decimal>("CreditAmount")
                                .HasColumnType("decimal(18, 2)");

                            b1.Property<decimal>("DebitAmount")
                                .HasColumnType("decimal(18, 2)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<Guid>("JournalEntryId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("JournalEntryId");

                            b1.ToTable("LedgerEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JournalEntryId");
                        });

                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
